package test.dao;

import java.util.List;
import test.model.SysRolePrivilege;

public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated Thu Apr 26 19:58:25 CST 2018
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated Thu Apr 26 19:58:25 CST 2018
     */
    List<SysRolePrivilege> selectAll();
}